## Service definition ##
application:
  schemaVersion: 1.0.0-preview1
  name: ToDoListApp
  properties:
    services:
      - name: WebFrontEnd
        properties:
          description: WebFrontEnd description.
          osType: Windows
          codePackages:
            - name: WebFrontEnd
              image: webfrontend:dev
              endpoints:
                - name: WebFrontEndListener
                  port: 20008
              environmentVariables:
                - name: ASPNETCORE_URLS
                  value: http://+:20008
#                - name: ApplicationInsights:InstrumentationKey
#                  value: "<Place AppInsights key here, or reference it via a secret>"
              resources:
                requests:
                  cpu: 0.5
                  memoryInGB: 1
          replicaCount: 1
          networkRefs:
            - name: ToDoListAppNetwork